version: "3.8"

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: timescaledb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example_password
      - POSTGRES_DB=metrics_db
    ports:
      - "6681:5432"
    volumes:
      - timescaledb-data:/var/lib/postgresql/data

  nats:
    image: nats:latest
    container_name: nats-server
    ports:
      - "6682:4222" # Client connections
      - "6683:6222" # Routes
      - "6684:8222" # Monitoring
    command: "--name main --jetstream --http_port 8222"
    volumes:
      - jetstream-data:/tmp/nats/jetstream

volumes:
  timescaledb-data:
    driver: local
  jetstream-data:
    driver: local
