communication:
    state_stream_name: controller-state
    commands_stream_name: controller-commands
    plug_name: plug_bitaxe_001

controller:
    controller:
        action_interval: 10s
    sensor_data:
        update_interval: 5s
        control_duration: 1min
    switch:
        debounce_duration: 30s
    miner:
        demand: 30
    battery:
        low_threshold: 10.
        high_threshold: 30.
