version: "3.8"

services:
  nats:
    image: nats:latest
    ports:
      - "1883:1883" # MQTT client connections
      - "4222:4222" # NATS Client connections
      - "6222:6222" # Routes
      - "8222:8222" # Monitoring
    command: "-c /nats.conf"
    volumes:
      - ~/jetstream-data:/data/jetstream
      - ./nats.conf:/nats.conf:ro
    restart: unless-stopped

  solaredge:
    image: ghcr.io/deroetzi/solaredge2mqtt:latest
    env_file:
      - ./.env
    secrets:
      - se2mqtt_mqtt__password
    restart: unless-stopped

  influxdb:
    image: influxdb:3-core
    ports:
      - 8181:8181
    command:
      - influxdb3
      - serve
      - --node-id=node0
      - --object-store=file
      - --data-dir=/var/lib/influxdb3
    restart: unless-stopped

secrets:
  se2mqtt_mqtt__password:
    file: .secrets/mqtt_password
